### ISSUE TITLE
Creating Contracts using Foundry

### ISSUE THREAD

**Issue by ShivRaiGithub** [SpandanM110/Ethpreneur#12]
Hey, I wasn't able to find a `.sol` file in the repo so I presume the smart contracts are written yet.
I would like to implement the smart contract part using Foundry, a solidity framework.

A suggestion I have for implementation :
Shares in real life carry a unique identity like NFT but they are also broken into parts i.e. 10 shares, 20 shares. Since its practically impossible to mint that many NFTs for a single user buying for a single company, we should use ERC1155 for the implementation.
Benefits of using ERC1155 instead of NFTs :
1 - ERC1155 can represent unique data like name and symbol like NFTs
2 - It can be traded as parts like ERC20 i.e. 10 tokens, 20 tokens, etc.
Hence making it better than just NFTs as shares.

But like I said, its just a suggestion. I can still work on it in form of only NFTs if you want.

Please assign it to me under wob. Thank you.

**Comment by SpandanM110** [comment]
Yeah noted I am assigning you can work on it 

Good Luck!
